FROM jenkins/ssh-agent:jdk11

ENV DEBIAN_FRONTEND "noninteractive"
ENV JAVA_HOME "/usr/local/openjdk-11"
ENV JAVA_PATH "/usr/local/openjdk-11/bin"

USER root

# Install necessary dependencies
RUN apt-get update && apt-get install -y lsb-release git curl apt-transport-https ca-certificates software-properties-common gnupg2 

# Add Docker repository key
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

# Add Docker repository
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install Docker
RUN apt-get update && apt-get install -y docker-ce-cli

# Create a "docker" group and add the "jenkins" user to it
RUN groupadd -g 999 docker && usermod -aG docker jenkins


